language: elixir
sudo: false
elixir:
  - '1.6.4'
otp_release:
  - '20.0'
cache:
  directories:
    - _build
    - deps
before_install:
  - mkdir -p ~/.hex/
  - openssl aes-256-cbc -K $encrypted_212ad61caf9f_key -iv $encrypted_212ad61caf9f_iv -in hex.config.enc -out ~/.hex/hex.config -d
script:
  - wget http://www8.cao.go.jp/chosei/shukujitsu/syukujitsu_kyujitsu.csv
  - iconv -f Shift_JIS -t UTF8 syukujitsu_kyujitsu.csv > data.csv
  - MIX_ENV=test mix test
deploy:
  provider: script
  script: >-
    mix deps.get &&
    wget http://www8.cao.go.jp/chosei/shukujitsu/syukujitsu_kyujitsu.csv
    iconv -f Shift_JIS -t UTF8 syukujitsu_kyujitsu.csv > data.csv
    echo $HEX_LOCAL_PASSWORD | mix hex.publish --no-confirm &&
    mix clean &&
    mix deps.clean --all
